name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: |
          if [ -f bun.lockb ]; then
            curl -fsSL https://bun.sh/install | bash
            export BUN_INSTALL="$HOME/.bun"
            export PATH="$BUN_INSTALL/bin:$PATH"
            bun install
          else
            npm ci
          fi
      - name: Lint
        run: |
          if [ -f bun.lockb ]; then
            bun run lint || bunx eslint .
          else
            npm run lint
          fi
      - name: Type Check
        run: npx tsc --noEmit
      - name: Build
        run: |
          if [ -f bun.lockb ]; then
            bun run build
          else
            npm run build
          fi
